# Generated by Django 2.2.6 on 2020-01-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gender', models.CharField(choices=[('male', 'M'), ('Female', 'F'), ('None', 'N')], default='None', max_length=10)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_image', models.FileField(blank=True, null=True, upload_to='scans')),
                ('instance_number', models.PositiveIntegerField()),
                ('scan_type', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='brain.Patient')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
            },
        ),
    ]
