# Generated by Django 2.2.6 on 2020-01-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200111_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
