# Generated by Django 2.2.6 on 2020-01-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20200104_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
