# Generated by Django 2.2.6 on 2020-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_zip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZIP',
        ),
    ]
