# Generated by Django 2.2.6 on 2020-01-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_auto_20200104_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
