# Generated by Django 2.2.6 on 2020-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_delete_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='stage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
