# Generated by Django 2.2.6 on 2020-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_scan_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('Female', 'F'), ('None', 'N')], default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
