# Generated by Django 2.2.6 on 2020-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_auto_20200104_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_image',
            field=models.FileField(blank=True, null=True, upload_to='scans/'),
        ),
    ]
