# Generated by Django 2.2.6 on 2020-01-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_auto_20200124_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
