# Generated by Django 2.2.6 on 2020-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_auto_20200125_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
